### PR TITLE
Player animations

### PR DESCRIPTION
**Pull request by CajoAlbuquerque**
All player animations are implemented. You can do everything in three diferent states:
* with rifle
* with pistol
* without any weapon

Furthermore you can Melee, Die and WallRun on both sides.

### CODE REVIEW

**Comment by claudiarmamede** [comment]
image

The weapon seems to get out of the player's hands, even if it hasn't collided with anything...  (the same thing happens to the enemies @bernas670  @BernardoCMoreira )

(ps: death interaction looks great 🥇  )

**Comment by CajoAlbuquerque** [comment]
> image
> 
> The weapon seems to get out of the player's hands, even if it hasn't collided with anything... (the same thing happens to the enemies @bernas670 @BernardoCMoreira )
> 
> (ps: death interaction looks great 🥇 )

do you have any error in the console??

**Comment by BernardoCMoreira** [comment]
- [ ] I have the same error that claudia stated, and I don't know why that's happening. I tested it a lot, even changing weapons was working fine. And the enemies didn't had any problem with the rigging aswell. Probably you changed something by mistake?
- [ ] What happened to Rig layer? Enemie should have a rig layer with both RightHandIK and LeftHandIK
image


- [ ] Impact and muzzle flash are not working, it's probably the problem u said about materials, because prefabs also look like this : 
image

**Comment by CajoAlbuquerque** [comment]
Fixed everything guys! Please test and approve

**Review by BernardoCMoreira — APPROVED** [review]

**Pull request merged**
